apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: filestream
        id: kubernetes-containers
        paths:
          - /var/log/containers/*.log

        # REQUIRED for Kubernetes
        symlinks: true
        scan_frequency: 10s

        parsers:
          - container: ~

        multiline:
          pattern: '^(Exception|\s+at )'
          negate: false
          match: after

    processors:
      # Add k8s metadata FIRST
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      # Keep ONLY lab namespace
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "lab"

      # Decode JSON logs
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

    output.logstash:
      hosts: ["logstash.logging.svc.cluster.local:5044"]

    logging.level: debug
    logging.to_files: false
